tidyCI

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -41,7 +41,7 @@ jobs:
       - name: ccache
         uses: hendrikmuhs/ccache-action@v1.2
 
-      - name: report environment
+      - name: Report environment
         run:  uname -a && cmake --version && ccache -s
 
       - name: Configure CMake
@@ -90,10 +90,10 @@ jobs:
         with:
           files: "pysjef/build.sh"
 
-      - name: report environment
+      - name: Report environment
         run:  uname -a && cmake --version
 
-      - name: build and test
+      - name: Build
         run: |
           cd pysjef
           . /opt/conda/etc/profile.d/conda.sh
@@ -102,7 +102,7 @@ jobs:
           #ssh 127.0.0.1 pwd
           conda install -c conda-forge -y --file requirements.txt
           BUILD=cmake-build-$(uname)-$(uname -m)
-          cmake -S .. -B $BUILD -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TESTS=OFF -DBUILD_PROGRAM=OFF || { echo 'cmake configuration failed' ; exit 1; }
+          cmake -S .. -B $BUILD -DBUILD_TESTS=OFF -DBUILD_PROGRAM=OFF || { echo 'cmake configuration failed' ; exit 1; }
           cmake --build $BUILD -t install || { echo 'cmake install failed' ; exit 1; }
           export CXXFLAGS='-std=c++17'
           uname | grep -q Darwin && export CXXFLAGS="$CXXFLAGS -mmacosx-version-min=13"
