tidyCI

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -99,9 +99,14 @@ jobs:
           . /opt/conda/etc/profile.d/conda.sh
           mkdir -p /var/run/sshd
           /usr/sbin/sshd
-          ssh 127.0.0.1 pwd
-          conda create -c conda-forge -n pysjef -y --file requirements.txt
-          conda activate pysjef
-          bash ./build.sh
-          pytest
+#          ssh 127.0.0.1 pwd
+          conda install -c conda-forge -y --file requirements.txt
+          BUILD=cmake-build-$(uname)-$(uname -m)
+          cmake -S .. -B $BUILD -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TESTS=OFF -DBUILD_PROGRAM=OFF || { echo 'cmake configuration failed' ; exit 1; }
+          cmake --build $BUILD -t install || { echo 'cmake install failed' ; exit 1; }
+          export CXXFLAGS='-std=c++17'
+          uname | grep -q Darwin && export CXXFLAGS="$CXXFLAGS -mmacosx-version-min=13"
+          python -m pip install .
+      - name: Test
+        run: pytest
 
